import { 
  BarChart3, 
  TrendingUp, 
  Package, 
  Layers, 
  Receipt, 
  Factory, 
  DollarSign,
  History,
  Users,
  AlertCircle
} from 'lucide-react';
import { ReportDefinition } from './types';
import * as functions from './services/reportFunctions';

export const REPORT_REGISTRY: ReportDefinition[] = [
  {
    id: 'ventas-periodo',
    title: 'Ventas por Período',
    category: 'VENTAS',
    description: 'Tendencia diaria de ingresos y utilidad bruta.',
    icon: TrendingUp,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runVentasPeriodo,
    columns: [
      { label: 'Fecha', key: 'date', format: 'string' },
      { label: 'Ingresos', key: 'sales', format: 'currency' },
      { label: 'Utilidad', key: 'profit', format: 'currency' },
      { label: 'Operaciones', key: 'count', format: 'number' },
      { label: 'Ticket Prom.', key: 'avgTicket', format: 'currency' },
      { label: 'Margen %', key: 'margin', format: 'percent' },
    ],
    chart: { type: 'line', xKey: 'date', yKeys: ['sales', 'profit'] },
    exports: ['xlsx', 'csv'],
  },
  {
    id: 'ventas-linea',
    title: 'Ventas por Línea de Negocio',
    category: 'VENTAS',
    description: 'Distribución de ingresos entre las 5 líneas activas.',
    icon: BarChart3,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runVentasLinea,
    columns: [
      { label: 'Línea', key: 'line', format: 'string' },
      { label: 'Ingresos', key: 'sales', format: 'currency' },
      { label: 'Utilidad', key: 'profit', format: 'currency' },
      { label: 'Unidades', key: 'units', format: 'number' },
      { label: 'Margen %', key: 'margin', format: 'percent' },
    ],
    chart: { type: 'donut', xKey: 'line', yKeys: ['sales'] },
    exports: ['xlsx'],
  },
  {
    id: 'valorizacion-stock',
    title: 'Valorización de Stock',
    category: 'INVENTARIO',
    description: 'Capital inmovilizado en producto terminado por línea.',
    icon: Package,
    filters: [],
    run: functions.runValorizacionStock,
    columns: [
      { label: 'SKU', key: 'sku', format: 'string' },
      { label: 'Línea', key: 'line', format: 'string' },
      { label: 'Stock', key: 'qty', format: 'number' },
      { label: 'Costo Prom.', key: 'avgCost', format: 'currency' },
      { label: 'Valor Total', key: 'totalValue', format: 'currency' },
    ],
    chart: { type: 'donut', xKey: 'sku', yKeys: ['totalValue'] },
    exports: ['xlsx', 'pdf'],
  },
  {
    id: 'consumo-bobina',
    title: 'Consumo de Bobina por Línea',
    category: 'MATERIA_PRIMA',
    description: 'Kg de acero consumidos para transformación por cada línea.',
    icon: Layers,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runConsumoBobina,
    columns: [
      { label: 'Línea', key: 'line', format: 'string' },
      { label: 'Consumo (Kg)', key: 'kg', format: 'number' },
      { label: 'Piezas Prod.', key: 'pieces', format: 'number' },
      { label: 'Rendimiento %', key: 'yield', format: 'percent' },
    ],
    chart: { type: 'bar', xKey: 'line', yKeys: ['kg'] },
    exports: ['xlsx'],
  },
  {
    id: 'rentabilidad',
    title: 'Rentabilidad por Producto',
    category: 'VENTAS',
    description: 'Ranking de productos más rentables (Margen Bruto vs Costo).',
    icon: DollarSign,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runRentabilidad,
    columns: [
      { label: 'SKU', key: 'sku', format: 'string' },
      { label: 'Ingresos', key: 'sales', format: 'currency' },
      { label: 'Utilidad', key: 'profit', format: 'currency' },
      { label: 'Unid.', key: 'units', format: 'number' },
      { label: 'Margen', key: 'margin', format: 'percent' },
    ],
    chart: { type: 'bar', xKey: 'sku', yKeys: ['profit'] },
    exports: ['xlsx'],
  },
  {
    id: 'cotizaciones',
    title: 'Embudo de Cotizaciones',
    category: 'VENTAS',
    description: 'Análisis de conversión: Cotizaciones registradas vs Ventas cerradas.',
    icon: Receipt,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runCotizaciones,
    columns: [
      { label: 'Métrica', key: 'metric', format: 'string' },
      { label: 'Valor', key: 'value', format: 'string' },
    ],
    exports: ['xlsx'],
  },
  {
    id: 'sunat-igv',
    title: 'Reporte Tributario (IGV)',
    category: 'VENTAS',
    description: 'Base imponible e IGV de ventas completadas para declaración.',
    icon: BarChart3,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runSunatIGV,
    columns: [
      { label: 'ID', key: 'id', format: 'string' },
      { label: 'Fecha', key: 'date', format: 'string' },
      { label: 'Cliente', key: 'customer', format: 'string' },
      { label: 'Base', key: 'base', format: 'currency' },
      { label: 'IGV', key: 'igv', format: 'currency' },
      { label: 'Total', key: 'total', format: 'currency' },
    ],
    exports: ['xlsx', 'csv'],
  },
  {
    id: 'stock-bajo',
    title: 'Alertas de Stock Bajo',
    category: 'INVENTARIO',
    description: 'Productos terminados con existencias por debajo del umbral de seguridad.',
    icon: AlertCircle,
    filters: [],
    run: functions.runStockBajo,
    columns: [
      { label: 'SKU', key: 'sku', format: 'string' },
      { label: 'Línea', key: 'line', format: 'string' },
      { label: 'Existencia', key: 'qty', format: 'number' },
      { label: 'Umbral', key: 'threshold', format: 'number' },
    ],
    exports: ['xlsx'],
  },
  {
    id: 'valorizacion-coils',
    title: 'Valorización de Materia Prima',
    category: 'MATERIA_PRIMA',
    description: 'Valorización del pool de bobinas por acabado y proveedor.',
    icon: Layers,
    filters: [],
    run: functions.runValorizacionCoils,
    columns: [
      { label: 'Acabado', key: 'finish', format: 'string' },
      { label: 'Peso (Kg)', key: 'kg', format: 'number' },
      { label: 'Valorización', key: 'value', format: 'currency' },
      { label: 'Precio Prom/Kg', key: 'avgPrice', format: 'currency' },
    ],
    chart: { type: 'donut', xKey: 'finish', yKeys: ['value'] },
    exports: ['xlsx', 'pdf'],
  },
  {
    id: 'produccion-detalle',
    title: 'Producción Detallada',
    category: 'PRODUCCIÓN',
    description: 'Listado exhaustivo de órdenes de producción ejecutadas.',
    icon: Factory,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runProduccionDetalle,
    columns: [
      { label: 'ID', key: 'id', format: 'string' },
      { label: 'Fecha', key: 'date', format: 'string' },
      { label: 'Línea', key: 'line', format: 'string' },
      { label: 'SKU', key: 'sku', format: 'string' },
      { label: 'Piezas', key: 'pieces', format: 'number' },
      { label: 'Kg Cons.', key: 'kg', format: 'number' },
      { label: 'Merma', key: 'scrap', format: 'number' },
      { label: 'Operador', key: 'operator', format: 'string' },
    ],
    exports: ['xlsx'],
  },
  {
    id: 'margen-bruto',
    title: 'Margen Bruto Ejecutivo',
    category: 'EJECUTIVO',
    description: 'Estado de ganancias y pérdidas simplificado por línea.',
    icon: BarChart3,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: functions.runMargenBruto,
    columns: [
      { label: 'Línea', key: 'line', format: 'string' },
      { label: 'Ventas (S/)', key: 'sales', format: 'currency' },
      { label: 'Costo (S/)', key: 'cost', format: 'currency' },
      { label: 'Utilidad (S/)', key: 'profit', format: 'currency' },
      { label: 'Margen %', key: 'margin', format: 'percent' },
    ],
    chart: { type: 'bar', xKey: 'line', yKeys: ['sales', 'profit'] },
    exports: ['xlsx', 'pdf'],
  },
  {
    id: 'kardex',
    title: 'Kardex de Movimientos',
    category: 'INVENTARIO',
    description: 'Historial detallado de entradas y salidas (Formato SUNAT).',
    icon: History,
    filters: [
      { id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' },
      { id: 'sku', label: 'Filtrar por SKU', type: 'TEXT' }
    ],
    run: functions.runKardex,
    columns: [
      { label: 'Fecha', key: 'date', format: 'string' },
      { label: 'SKU', key: 'sku', format: 'string' },
      { label: 'Tipo', key: 'type', format: 'badge', badgeStyle: (v) => v === 'IN' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' },
      { label: 'Cant.', key: 'quantity', format: 'number' },
      { label: 'Saldo', key: 'balance', format: 'number' },
      { label: 'Referencia', key: 'reference', format: 'string' },
      { label: 'Descripción', key: 'description', format: 'string' },
    ],
    exports: ['xlsx', 'csv'],
  },
  // --- P2 PLACEHOLDERS ---
  {
    id: 'ventas-por-producto',
    title: 'Ventas por Producto (SKU)',
    category: 'VENTAS',
    description: 'Acumulado vendido por cada producto: cantidad, monto, margen, # ventas y # clientes.',
    icon: Package,
    filters: [
      { id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'HISTORICO' },
      { id: 'line', label: 'Línea de Negocio', type: 'LINE', defaultValue: 'all' },
      { id: 'search', label: 'Buscar SKU/Nombre', type: 'TEXT' },
      { id: 'includeVoided', label: 'Incluir Anuladas', type: 'BOOLEAN', defaultValue: false }
    ],
    run: functions.runVentasPorProducto,
    columns: [
      { label: 'SKU', key: 'sku', format: 'string' },
      { label: 'Producto', key: 'productName', format: 'string' },
      { label: 'Línea', key: 'line', format: 'badge', badgeStyle: (v) => {
        const styles: Record<string, string> = {
          drywall: 'bg-blue-100 text-blue-700',
          roofing: 'bg-green-100 text-green-700',
          'metallic-roofing': 'bg-slate-100 text-slate-700',
          trading: 'bg-purple-100 text-purple-700',
          services: 'bg-orange-100 text-orange-700'
        };
        return styles[v] || 'bg-slate-100 text-slate-700';
      }},
      { label: 'Cant. Total', key: 'quantity', format: 'number' },
      { label: 'Monto (S/)', key: 'amount', format: 'currency' },
      { label: 'Utilidad (S/)', key: 'profit', format: 'currency', roles: ['ADMIN', 'SUPERVISOR'] },
      { label: 'Margen %', key: 'margin', format: 'percent', roles: ['ADMIN', 'SUPERVISOR'], badgeStyle: (v) => v < 10 ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700' },
      { label: 'N° Ventas', key: 'numSales', format: 'number' },
      { label: 'N° Clientes', key: 'numCustomers', format: 'number' },
    ],
    chart: { type: 'bar', xKey: 'sku', yKeys: ['amount'] },
    exports: ['xlsx', 'csv'],
  },
  {
    id: 'ventas-cliente',
    title: 'Análisis de Clientes (Pareto)',
    category: 'VENTAS',
    description: 'Concentración de ventas y ranking de mejores clientes.',
    icon: Users,
    filters: [{ id: 'period', label: 'Período', type: 'PERIOD', defaultValue: 'MES' }],
    run: async () => ({ rows: [] }),
    columns: [],
    exports: ['xlsx'],
  },
  {
    id: 'trazabilidad',
    title: 'Trazabilidad de Bobina',
    category: 'PRODUCCIÓN',
    description: 'Seguimiento desde la bobina madre hasta el cliente final.',
    icon: History,
    filters: [{ id: 'sku', label: 'Serie de Bobina', type: 'TEXT', required: true }],
    run: async () => ({ rows: [] }),
    columns: [],
    exports: ['xlsx', 'pdf'],
  }
];
